services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    environment:
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 81:80
    restart: always
    environment:
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres-data:
  pgadmin-data:
